fix compiler complaint about `strptime`
from @facchinm :
compilation fails due to
`error: 'strptime' was not declared in this scope` 
which is in fact fixed by `_XOPEN_SOURCE patch`